# Generated by Django 4.1.3 on 2022-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0008_remove_platos_producto_platos_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platos',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='platos',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
