# Generated by Django 4.1.3 on 2022-12-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0009_remove_platos_cantidad_alter_platos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
