# Generated by Django 4.1.3 on 2022-12-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0010_product_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('precio', models.FloatField(default=0.0)),
                ('producto', models.ManyToManyField(blank=True, to='e_shop.product', verbose_name='producto')),
            ],
        ),
    ]
