# Generated by Django 4.1.3 on 2022-12-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0011_combos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platos',
        ),
    ]
